### PR TITLE
MySQL 5 compat and CMB2/cmb2 unification

### PR DESCRIPTION
**Pull request by joeytwiddle**
When I deployed to Ubuntu 14.04 (trusty) server, I had two problems:
- MB tried to create some new tables, but there was an error:
  
  ```
  The used table type doesn't support FULLTEXT indexes for query CREATE TABLE .....
  ```
- In `init.php` one of the `require_once`s was failing, because it was looking in `cmb2` for a file which was in `CMB2`!

(Note: I also exported my DB, added `ENGINE=MyISAM` to all tables, and then re-imported it. I don't know if that was a necessary step or not!)

By the way, is there documentation for the shortcodes somewhere? I would like to use a bookgrid shortcode with LayersWP, and ideally filter it by tags or maybe categories.

Cheers!

### CODE REVIEW

**Comment by christiespeich** [comment]
Thanks for this, joeytwiddle.

I need to look more into the MyISAM vs InnoDB ... On my local Wordpress, InnoDB is used for the tables, so I'm hesitant to use MyISAM and I really don't know enough about the differences between them. I also notice that Wordpress does not index the post_content column, so perhaps I don't need to  or shouldn't index the summary, excerpt, and info fields for books.  If I remove the fulltext indices on those fields, it should solve the problem, correct?

As a side note, I'm really not very good at making sure master is in a "good" place. I forget that other people could be looking at this code as well, not just users from Wordpress. I will work on being more conscientious of doing development in branches, merging, and committing more often. As it is right now I have a slew of updates to commit. While I will work to get better, please be cautious of using code from master in between releases.

As to shortcodes, no I don't have any documentation anywhere at this time. There currently isn't a bookgrid shortcode. I can consider it for a future release. I'm getting ready to release version 3.0. Was going to do it this weekend, but now will wait until I figure out this MyISAM vs InnoDB issue....

**Comment by christiespeich** [comment]
Okay, after going through hell trying to get cmb2 renamed to CMB2, I realized a couple of things:
- My production websites, and surely many, many of the ones run by other users of Mooberry Book Manager, are run on *nix servers, not Windows. There has never been any problems with the capitalization of cmb2.
- There are no `require_once` calls in `init.php` that reference a directory.... so I'm not sure why you are getting an error there?

At this time, cmb2 is going to remain cmb2.

**Comment by joeytwiddle** [comment]
Thanks for bringing all the files together into one folder. I too found it quite troublesome when I attempted it.
- The problem was `require_once 'bootstrap.php'` failed because bootstrap.php was in the `CIMB2` folder while init.php was in `cimb2` folder.
- I now believe this was only an issue because I cloned the plugin with git. When the plugin is distributed normally (by zip file?) it appears that all the files get collected into just one `CIMB2` folder.

Anyway I am happy to report it is resolved in your latest version, even for git users on Linux!

Thanks for the warning about `master` too. We will tread carefully.

**Comment by joeytwiddle** [comment]
As for the [MyISAM](http://stackoverflow.com/questions/20148/myisam-versus-innodb#6796566) versus [InnoDB](https://en.wikipedia.org/wiki/Comparison_of_MySQL_database_engines) question, I know little about DB engines. I can only offer some suggestions:
- Warn users not to install MooberryBM version 3.0 if they are running MySQL below v5.6.4. (Is this possible pre-installation? One less desirable way might be to name the product "Mooberry Book Plugin for MySQL5")
  or
- Detect the running version of MySQL and create the table using MyISAM only on those systems which need it.

It turns out that MySQL 5.6.28 is available for Ubuntu 14.04, so it will not be difficult for us to upgrade, but the system didn't automatically upgrade it, hence why we are still running 5.5.

**Comment by christiespeich** [comment]
How strange that it was in two folders. It's a library that I just copied into the project. Either way, I'm glad it's resolved now.

As to the database issue, I removed the fulltext indices so hopefully that will work. Should we decide that the indices are necessary we can look into how to add them safely.   

Thanks!

**Comment by joeytwiddle** [comment]
Cheers! We are grateful for your plugin and we would like to make a donation. But I can't seem to find the PayPal link today. Will it be coming back?

**Pull request closed without merging**
